-- MySQL Workbench Synchronization
-- Generated: 2017-08-28 20:35
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Octavio Ruiz Castillo

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `omoikane`.`articulos`
ADD COLUMN `CLAVE_PRODUCTO_SAT_CLAVE` VARCHAR(16) NOT NULL AFTER `departamento_id`,
ADD COLUMN `CLAVE_UNIDAD_SAT_CLAVE` VARCHAR(8) NOT NULL AFTER `CLAVE_PRODUCTO_SAT_CLAVE`,
ADD INDEX `fk_articulos_CLAVE_PRODUCTO_SAT1_idx` (`CLAVE_PRODUCTO_SAT_CLAVE` ASC),
ADD INDEX `fk_articulos_CLAVE_UNIDAD_SAT1_idx` (`CLAVE_UNIDAD_SAT_CLAVE` ASC);

CREATE TABLE IF NOT EXISTS `omoikane`.`CLAVE_PRODUCTO_SAT` (
  `CLAVE` VARCHAR(16) NOT NULL,
  `DESCRIPCION` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`CLAVE`))
ENGINE=InnoDB  DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

CREATE TABLE IF NOT EXISTS `omoikane`.`CLAVE_UNIDAD_SAT` (
  `CLAVE` VARCHAR(8) NOT NULL,
  `NOMBRE` VARCHAR(255) NOT NULL,
  `DESCRIPCION` VARCHAR(255) NULL DEFAULT NULL,
  `SIMBOLO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CLAVE`))
ENGINE=InnoDB  DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

ALTER TABLE `omoikane`.`articulos`
ADD CONSTRAINT `fk_articulos_CLAVE_PRODUCTO_SAT1`
  FOREIGN KEY (`CLAVE_PRODUCTO_SAT_CLAVE`)
  REFERENCES `omoikane`.`CLAVE_PRODUCTO_SAT` (`CLAVE`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `fk_articulos_CLAVE_UNIDAD_SAT1`
  FOREIGN KEY (`CLAVE_UNIDAD_SAT_CLAVE`)
  REFERENCES `omoikane`.`CLAVE_UNIDAD_SAT` (`CLAVE`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
